# Generated by Django 3.2.9 on 2021-11-10 12:02

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='RoleOfStartUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='StartUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('is_actual', models.BooleanField()),
                ('creation_datetime', models.DateTimeField()),
                ('description', models.CharField(max_length=2048)),
                ('max_members_count', models.SmallIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='startupapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('first_name', models.CharField(max_length=64)),
                ('middle_name', models.CharField(max_length=64, null=True)),
                ('last_name', models.CharField(max_length=64)),
                ('user_image', models.ImageField(null=True, upload_to='')),
                ('register_date', models.DateTimeField()),
                ('emails', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), size=None)),
                ('phones', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), size=None)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='startupapp.region')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='startupapp.typeofuser')),
            ],
        ),
        migrations.CreateModel(
            name='UserStartupInvestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invest_datetime', models.DateTimeField()),
                ('invested_money', models.DecimalField(decimal_places=2, max_digits=9)),
                ('invest_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='startupapp.typeoftransaction')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='startupapp.startup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='startupapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserLoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_success', models.BooleanField()),
                ('ip_address', models.GenericIPAddressField()),
                ('login_datetime', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startupapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='StartUpOfUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startupapp.roleofstartup')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startupapp.startup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startupapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='StartUpImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(max_length=64)),
                ('image_description', models.CharField(max_length=2048)),
                ('upload_datetime', models.DateTimeField()),
                ('image_blob', models.ImageField(upload_to='')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startupapp.startup')),
            ],
        ),
        migrations.CreateModel(
            name='StartUpComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2048)),
                ('post_datetime', models.DateTimeField()),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startupapp.startup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startupapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=32)),
                ('startups', models.ManyToManyField(to='startupapp.StartUp')),
            ],
        ),
    ]
