# Generated by Django 3.2.9 on 2021-11-10 12:07

from django.db import migrations, models


def insert_user_types(apps, schema_editor):
    """Inserts predefined user types into the database."""
    for user_type_name in ('Пользователь',
                           'Администратор',
                           'Модератор'):
        TypeOfUser = apps.get_model('startupapp', 'TypeOfUser')
        current_type = TypeOfUser()
        current_type.name = user_type_name
        current_type.save()


def insert_role_types(apps, schema_editor):
    """Inserts predefined startup role types into the database."""
    for role_type_name in ('Участник',
                           'Волонтёр',
                           'Организатор'):
        RoleOfStartUp = apps.get_model('startupapp', 'RoleOfStartUp')
        current_type = RoleOfStartUp()
        current_type.name = role_type_name
        current_type.save()


def insert_transaction_types(apps, schema_editor):
    """Inserts predefined transcation types into the database."""
    for transaction_type_name in ('Пользователь',
                                  'Модератор',
                                  'Администратор'):
        TypeOfTransaction = apps.get_model('startupapp', 'TypeOfTransaction')
        current_type = TypeOfTransaction()
        current_type.name = transaction_type_name
        current_type.save()


class Migration(migrations.Migration):
    dependencies = [
        ('startupapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_user_types),
        migrations.RunPython(insert_role_types),
        migrations.RunPython(insert_transaction_types),
    ]
