# Generated by Django 3.2.9 on 2021-11-10 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startupapp', '0003_auto_20211110_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupimage',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='startupapp.user'),
        ),
    ]
