# Generated by Django 3.2.9 on 2021-11-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupapp', '0005_user_money_in_rubles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupimage',
            name='image_blob',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
