# Generated by Django 3.2.9 on 2021-11-11 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startupapp', '0006_alter_startupimage_image_blob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupimage',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='startupapp.user'),
        ),
    ]
